FROM oven/bun:1

ARG DB_URL
ENV DATABASE_URL={DB_URL}

WORKDIR /usr/src/app

COPY . .

RUN bun run db:generate
RUN DATABASE_URL=${DB_URL} bunx turbo build --filter=web...

EXPOSE 3000

CMD ["bun", "run", "start:web"]